Repository 202306-NEA-DZ-FEW/team-nine-capstone, pull requests merged in 2023-11, with the labels that each got.

#52 link events to users
  src/components/eventsPageComponents/EventCard.jsx
  src/components/eventsPageComponents/IEvents.jsx
  src/components/navbar/Navbar.jsx
  src/components/singlEventPageComponents/EditEvent.jsx
  src/components/singlEventPageComponents/EventDetails.jsx
  src/pages/authentication/signIn/index.jsx
  src/pages/authentication/signUp/index.jsx
  src/pages/events/myEvents/index.jsx
Labels: bug, enhancement, Bonus

#54 fix(YourEvents): filter users own collection
  next.config.js
  src/components/eventsPageComponents/IEvents.jsx
  src/components/eventsPageComponents/YourEvents.jsx
  src/components/navbar/Navbar.jsx
  src/pages/404.jsx
  src/pages/500.jsx
  src/pages/_error.jsx
  src/pages/createTheEvent/index.jsx
  src/pages/events/[id].jsx
  src/pages/events/editEvent/[id].jsx
  src/pages/events/yourEvents/index.jsx
Labels: bug, enhancement, Prioritise, Bonus

#57 56 implement a social share feature
  package-lock.json
  package.json
  src/components/eventsPageComponents/YourEvents.jsx
  src/components/homepage/HowitWorks.jsx
  src/components/reusableComponents/SocialShare.jsx
  src/components/singlEventPageComponents/EventDetails.jsx
  src/styles/globals.css
Labels: enhancement, Bonus

#71 styling, translation & notification of auth pages
  next-i18next.config.js
  public/images/background.png
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/navbar/Navbar.jsx
  src/components/reusableComponents/TermsAndConditions.jsx
  src/pages/authentication/signIn/index.jsx
  src/pages/authentication/signUp/index.jsx
Labels: enhancement

#95 fix(join btn, profile, events pages, event card)
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/eventsPageComponents/EventCard.jsx
  src/components/eventsPageComponents/EventList.jsx
  src/components/reusableComponents/JoinButton.jsx
  src/components/reusableComponents/UserProfileEventCard.jsx
  src/lib/firebase/controller.js
  src/pages/profile/[id].jsx
  src/pages/profile/[id]/editProfile/index.jsx
  src/pages/profile/[id]/events/index.jsx
Labels: bug, enhancement, Bonus

#92 fix(herosection): implment Translation
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/homepage/HeroSection.jsx
Labels: bug

#90 feat(editevent, createevent): implement Translation
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/createEventPageComponents/CreateEvent.jsx
  src/components/eventsPageComponents/EventCard.jsx
  src/components/homepage/HowitWorks.jsx
  src/components/singlEventPageComponents/EditEvent.jsx
  src/components/singlEventPageComponents/EventDetails.jsx
  src/pages/createTheEvent/index.jsx
  src/pages/events/editTheEvent/[id].jsx
  src/styles/globals.css
Labels: enhancement

#103 93 enhance page header social share panel
  next.config.js
  public/favicon.ico
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/EditProfileComponenets/updateSignInDetails.jsx
  src/components/aboutus/AboutUs.jsx
  src/components/createEventPageComponents/CreateEvent.jsx
  src/components/eventsPageComponents/EventList.jsx
  src/components/homepage/HowitWorks.jsx
  src/components/homepage/SectionTwo.jsx
  src/components/loader/Loader.jsx
  src/components/navbar/Navbar.jsx
  src/components/reusableComponents/ForgotPassword.jsx
  src/components/reusableComponents/SocialShare.jsx
  src/components/singlEventPageComponents/EditEvent.jsx
  src/components/singlEventPageComponents/EventDetails.jsx
  src/pages/_app.jsx
  src/pages/about/index.jsx
  src/pages/authentication/forgotPassword/index.jsx
  src/pages/authentication/signIn/index.jsx
  src/pages/authentication/signUp/index.jsx
  src/pages/createTheEvent/index.jsx
  src/pages/events/[id].jsx
  src/pages/events/index.jsx
  src/pages/index.jsx
  src/pages/profile/[id].jsx
  src/pages/profile/[id]/editProfile/index.jsx
  src/pages/profile/[id]/events/index.jsx
  src/pages/termsAndConditions.jsx
  src/styles/globals.css
Labels: enhancement

#115 108 edit event create event reset password components unit test
  next.config.js
  public/globalGoalsLogos/feedback3.jpg
  public/globalGoalsLogos/feedback5.jpg
  public/globalGoalsLogos/feedback6.jpg
  public/images/AboutUs/donation.png
  public/images/AboutUs/fakeImad.jpg
  public/images/donation.png
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/homepage/HowitWorks.jsx
  src/components/homepage/SectionTwo.jsx
  src/components/navbar/Navbar.jsx
Labels: bug
