Repository 202306-NEA-DZ-FEW/team-nine-capstone, pull requests merged in 2023-10, with the labels that each got.

#17 4-authentification 5 initiate database address Pr Changes
  .gitignore
  package-lock.json
  package.json
  public/images/Square.png
  src/components/eventsPageComponents/EventCard.jsx
  src/components/eventsPageComponents/EventList.jsx
  src/components/footer/Footer.jsx
  src/components/footer/__test__/Footer.test.js
  src/components/footer/__test__/__snapshots__/Footer.test.js.snap
  src/components/navbar/Navbar.jsx
  src/components/navbar/__test__/Navbar.test.js
  src/components/navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/lib/firebase/controller.js
  src/lib/firebase/firebase.js
  src/pages/authentication/signIn/index.jsx
  src/pages/authentication/signUp/index.jsx
  src/pages/authentification/index.js
  src/pages/createEvent/index.jsx
  src/pages/events/index.jsx
  src/pages/index.jsx
  src/styles/globals.css
Labels: bug, duplicate, Prioritise

#18 User State Management
  src/components/eventsPageComponents/EventCard.jsx
  src/components/footer/Footer.jsx
  src/components/navbar/Navbar.jsx
  src/context/UserContext.js
  src/layout/Layout.jsx
  src/pages/_app.jsx
  src/pages/authentication/signIn/index.jsx
  src/pages/authentication/signUp/index.jsx
  src/pages/events/index.jsx
  src/pages/index.jsx
Labels: enhancement, Prioritise, secondary, Bonus

#24 linking users auth to a users collection
  src/components/navbar/Navbar.jsx
  src/lib/firebase/controller.js
  src/pages/authentication/signUp/index.jsx
  src/pages/profile/[id].jsx
  src/pages/profile/editProfile/index.jsx
  src/pages/profile/events/index.jsx
Labels: enhancement, Prioritise

#26 feat(create event): add and create new event feature
  src/components/creatEventPageComponents/CreateEvent.jsx
  src/pages/createEvent/index.jsx
  src/pages/index.jsx
Labels: enhancement

#23 feat(add single event page, edit event )
  next.config.js
  src/components/createEventPageComponents/CreateEvent.jsx
  src/components/createEventPageComponents/TermsAndConditions.jsx
  src/components/eventsPageComponents/EventCard.jsx
  src/components/loader/Loader.jsx
  src/components/singlEventPageComponents/EditEvent.jsx
  src/components/singlEventPageComponents/EventDetails.jsx
  src/pages/createEvent/index.jsx
  src/pages/createTheEvent/index.jsx
  src/pages/events/[id].jsx
  src/pages/events/editEvent/[id].jsx
Labels: enhancement

#28 fix(home page section one): fix responsiveness and translation
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/homepage/HeroSection.jsx
  src/components/homepage/HowitWorks.jsx
Labels: enhancement

#29 edit profile page
  src/components/EditProfileComponenets/UserDetails.jsx
  src/components/EditProfileComponenets/updateSignInDetails.jsx
  src/lib/firebase/controller.js
  src/pages/authentication/signUp/index.jsx
  src/pages/profile/editProfile/index.jsx
Labels: enhancement

#35 display interrests and intrests selcotor for users
  src/components/EditProfileComponenets/UserDetails.jsx
  src/components/homepage/SectionTwo.jsx
  src/context/UserContext.js
  src/lib/firebase/controller.js
  src/lib/interestsList.js
  src/pages/authentication/signIn/index.jsx
  src/pages/profile/[id].jsx
Labels: enhancement

#43 initialize fire storage, image upload for avatar
  public/images/defaultUser.png
  src/components/EditProfileComponenets/AvatrInput.jsx
  src/components/EditProfileComponenets/UserDetails.jsx
  src/components/reusableComponents/LocationInput.jsx
  src/lib/firebase/controller.js
  src/pages/profile/[id].jsx
Labels: enhancement, Prioritise, Bonus

#41 feat(signup/signin): enable authentication providers
  public/locales/ar/common.json
  public/locales/en/common.json
  src/components/createEventPageComponents/TermsAndConditions.jsx
  src/components/footer/Footer.jsx
  src/lib/firebase/controller.js
  src/pages/authentication/signIn/index.jsx
  src/pages/authentication/signUp/index.jsx
  src/pages/termsAndConditions.jsx
Labels: enhancement, Prioritise, Bonus

#49 47 date categories location and interests functionality fix
  next.config.js
  package-lock.json
  package.json
  src/components/createEventPageComponents/CreateEvent.jsx
  src/components/eventsPageComponents/EventCard.jsx
  src/components/eventsPageComponents/EventList.jsx
  src/components/homepage/HowitWorks.jsx
  src/components/singlEventPageComponents/EditEvent.jsx
Labels: bug, enhancement, Bonus
